version: "3"

services:
    application:
        build: docker/application/.
        volumes:
            - ".:/var/www:rw"
        links:
            - mysql
        environment:
           - PYTHONUNBUFFERED=0 # for showing stdout in real time

    mysql:
        image: mysql:5.7
# not sure if usefull maybe for cli ?
#        ports:
#            - "3307:3306"
        restart: always
        volumes:
            - "./docker/data/mysql/:/var/lib/mysql/"
            - "./docker/log/mysql/:/var/log/mysql/"
        environment:
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "user"
            MYSQL_DATABASE: crawler
            MYSQL_ROOT_PASSWORD: "root"


# Comment phpmyadmin in PROD
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8072:80"
        links:
            - mysql:db
